/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigdecision;

import javax.swing.JTable;
import ttt.james.server.TTTWebService;
import ttt.james.server.TTTWebService_Service;

/**
 *
 * @author Colm
 */
public class MainMenuJFrame extends javax.swing.JFrame {
    private final TTTWebService service = new TTTWebService_Service().getTTTWebServicePort();
    private final MainCoordinator coordinator;
    private final int userId;
    
    /**
     * Creates new form MainMenuJFrame
     * @param coordinator
     * @param userId
     */
    public MainMenuJFrame(MainCoordinator coordinator, int userId) {
        this.coordinator = coordinator;
        this.userId = userId;
        initComponents();
        setLocationRelativeTo(null);
        setupGameTable();
    }
    
    private void setupGameTable() {
        String response = service.showOpenGames();
        
        switch(response) {
            case "ERROR-NOGAMES":
                gameTable.setModel(new GamesTableModel(new String[0][0]));
            case "ERROR-DB":
                errorLabel.setText("Error connecting to database.");
                break;
            default:
                GamesTableModel model = new GamesTableModel(response);
                gameTable.setModel(model);
                break;  
        }
    }
    
      private void joinGame() {
        int row = gameTable.getSelectedRow();
        if (row == -1) {
            return;
        }
        String value = gameTable.getValueAt(row, GamesTableModel.GAME_ID_COLUMN).toString();
        int gameId = Integer.parseInt(value);
        String response = service.joinGame(userId, gameId);
        switch (response) {
            case "ERROR-DB":
                break;
            case "0":
                break;
            case "1":
                coordinator.goToGameScreen(userId, gameId);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        myScoresButton = new javax.swing.JButton();
        leaderboardButton = new javax.swing.JButton();
        newGameButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameTable = new javax.swing.JTable();
        errorLabel = new javax.swing.JLabel();
        joinGameButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tic Tac Toe - Main Menu");

        myScoresButton.setText("My Scores");
        myScoresButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myScoresButtonActionPerformed(evt);
            }
        });

        leaderboardButton.setText("Leaderboard");
        leaderboardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaderboardButtonActionPerformed(evt);
            }
        });

        newGameButton.setText("New Game");
        newGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameButtonActionPerformed(evt);
            }
        });

        gameTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(gameTable);

        errorLabel.setForeground(new java.awt.Color(255, 0, 0));
        errorLabel.setText(" ");

        joinGameButton.setText("Join Game");
        joinGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                joinGameButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 367, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(myScoresButton)
                        .addGap(18, 18, 18)
                        .addComponent(leaderboardButton)
                        .addGap(18, 18, 18)
                        .addComponent(newGameButton)
                        .addGap(18, 18, 18)
                        .addComponent(joinGameButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(errorLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(myScoresButton)
                    .addComponent(leaderboardButton)
                    .addComponent(newGameButton)
                    .addComponent(joinGameButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void myScoresButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myScoresButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_myScoresButtonActionPerformed

    private void leaderboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaderboardButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderboardButtonActionPerformed

    private void newGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameButtonActionPerformed
        setupGameTable();
    }//GEN-LAST:event_newGameButtonActionPerformed

    private void joinGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_joinGameButtonActionPerformed
        joinGame();
    }//GEN-LAST:event_joinGameButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel errorLabel;
    private javax.swing.JTable gameTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton joinGameButton;
    private javax.swing.JButton leaderboardButton;
    private javax.swing.JButton myScoresButton;
    private javax.swing.JButton newGameButton;
    // End of variables declaration//GEN-END:variables
}
