/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bigdecision;

import ttt.james.server.TTTWebService; 
import ttt.james.server.TTTWebService_Service;

/**
 *
 * @author Manus
 */
public class MyScoresJFrame extends javax.swing.JFrame {
    private final TTTWebService service = new TTTWebService_Service().getTTTWebServicePort();
    private int userId;

    /**
     * Creates new form MyScoresJFrame
     */
    public MyScoresJFrame(int userId) {
        this.userId = userId;
        initComponents();
        setLabels();
        
    }
    
       private void setLabels() {
           int wins = 0;
           int losses = 0;
           int draws = 0;
        String response = service.showAllMyGames(userId);
        if(response.equals(ErrorCodes.NO_GAMES)) {
            errorLabel.setText("Error: No Games found.");
            return;
        }
        
        if(response.equals(ErrorCodes.DB)) {
            errorLabel.setText("Error connecting to Database");
            return;
        }
        
                
        String[] games = response.split("\n");
        for(String game: games) {
            String[] components = game.split(",");
            int gameId = Integer.parseInt(components[0]);
            String result = service.getGameState(gameId);
            switch(result){
                case"1":
                    if(components[1].equals(Constants.username))
                        wins += 1;
                    else
                        losses += 1;
                    break;
                case"2":
                    if(components[2].equals(Constants.username))
                        wins += 1;
                    else
                        losses += 1;
                    break;
                case"3":
                    draws += 1;
                default:
            }
        }
        winLabel.setText("Wins: " + wins);
        drawsLabel.setText("Draws: " + draws);
        lossesLabel.setText("Losses: " + losses);
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        errorLabel = new javax.swing.JLabel();
        winLabel = new javax.swing.JLabel();
        lossesLabel = new javax.swing.JLabel();
        drawsLabel = new javax.swing.JLabel();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        winLabel.setText("jLabel2");

        lossesLabel.setText("jLabel3");

        drawsLabel.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lossesLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drawsLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(winLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lossesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(drawsLabel)
                .addGap(226, 226, 226)
                .addComponent(errorLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel drawsLabel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lossesLabel;
    private javax.swing.JLabel winLabel;
    // End of variables declaration//GEN-END:variables

}
